# This is a basic workflow to help you get started with Actions

name: notify

on:
  - push

jobs:
  irc:
    runs-on: ubuntu-latest
    if: github.repository == 'countervandalism/CVNBot'
    steps:
    - name: Notify IRC
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'push'
      with:
        channel: "#cvn-bots"
        nickname: GitHub
        message: "${{ github.actor }} pushed to ${{ github.repository }}#${GITHUB_REF#'refs/heads/'} - ${{ github.event.compare }}"

